algoritmo "exercicio2_calc_area"
// Função : Elabore um algoritmo que leia o raio de uma
// circunferência,calcule e apresente sua área.
// Autor : Felipe Rocha - 2053667
// Data : 13/03/2018
// ENTRADA:  RAIO
// PROCESSAMENTO: A = PI * RAIO^2
// SAIDA:  AREA


// Seção de Declarações 
var

raio, area: real

inicio
// Seção de Comandos
escreva("Entre com o raio: ")
leia(raio)
area <- pi * raio^2
 
escreva(area)
 
fimalgoritmo
